### ISSUE TITLE
Can you please provide the fine tuning reference code ?

### ISSUE THREAD

**Issue by bhargavvmukti** [Ravi-Teja-konda/Surveillance_Video_Summarizer#1]
Hi @Ravi-Teja-konda : This is awesome work ! I am presently interested in fine tuning Florence-2 for my use case which aligns exactly with the work that you have done. Can you please add the training and validation codes to the repository ?

**Comment by AmjedKhaled165** [comment]
download
https://bit.ly/4gx42eQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Ravi-Teja-konda** [comment]
Hello @bhargavvmukti,

Thank you for your interest!

I’ve fine-tuned Florence-2 around its release. However, due to some other commitments, I won’t be able to release the training code at this moment.

In the meantime, feel free to check out this open-source Colab for reference:

[How to Fine-Tune Florence-2 on a Detection Dataset](https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/how-to-finetune-florence-2-on-detection-dataset.ipynb)

**Comment by bhargavvmukti** [comment]
Thanks @Ravi-Teja-konda for the inputs :


If not the code then  path forward if that can be shared would highly appreciate that !

This is for object detection ,for me the use case is video activity recognition like walking , running , sleeping  likewise on the surveillance data.

**Comment by Ravi-Teja-konda** [comment]
Sure , we can discuss if needed
I can help on that part
